---
- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - k3s
    - victoria-metrics
    - ceph-csi
  loop_control:
    loop_var: role

- name: Role Validation
  when: (ansible_run_tags in [(), ('all',)]) or ('ceph-csi' in ansible_run_tags)
  run_once: true
  block:
    - name: Validate project url
      ansible.builtin.uri:
        url: '{{ cephcsi_project.url }}/{{ cephcsi_project.tag }}'
        timeout: 5
      register: cephcsi_result
      delay: 1
      retries: 3
      until: cephcsi_result is not failed

    - name: Chart Validation
      block:
        - name: Update repository
          kubernetes.core.helm_repository:
            name: '{{ cephcsi_vars.kubernetes.helm.repository.org }}'
            repo_url: '{{ cephcsi_map.helm.repository.url }}'
            force_update: true

        - name: Validate cluster kubeconfig path
          ansible.builtin.stat:
            path: '{{ k3s_project.cluster.kubeconfig }}'
          register: cephcsi_kubeconfig
          changed_when: false

        - name: Get deployed chart release info
          kubernetes.core.helm_info:
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            name: '{{ cephcsi_vars.kubernetes.helm.chart.name }}'
            namespace: '{{ cephcsi_vars.kubernetes.namespace }}'
          register: cephcsi_release
          when: cephcsi_kubeconfig.stat.exists
          changed_when: false

        - name: Set comparison fact
          ansible.builtin.set_fact:
            cephcsi_comparison:
              chart: '{{ cephcsi_map.helm.chart.version }}'
              release: "{{ cephcsi_release.status.chart | default('0') | regex_search('[0-9.]+') }}"

        - name: Set chart postinstall fact
          ansible.builtin.set_fact:
            cephcsi_postinstall: false

        - name: Validate chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"
