---
- name: Load plaintext passwords (overrides vault if present)
  hosts: all
  gather_facts: false
  tags: always
  tasks:
    - name: Check for plaintext passwords
      ansible.builtin.stat:
        path: /etc/k3s-cluster/passwords.yaml
      register: plaintext_passwords
    - name: Load plaintext passwords
      ansible.builtin.include_vars:
        file: /etc/k3s-cluster/passwords.yaml
      when: plaintext_passwords.stat.exists

- name: Cluster Reset
  hosts: cluster
  become: true
  gather_facts: true
  serial:
    - 3
    - 5
  post_tasks:
    - name: Remove archived journal files
      ansible.builtin.command:
        cmd: journalctl --rotate --vacuum-time=1s
      changed_when: false
  tasks:
    - name: Get packages information
      ansible.builtin.package_facts:
      tags: always

    - name: Reset cluster
      ansible.builtin.include_role:
        name: '{{ reset }}'
        tasks_from: reset
      loop: '{{ global_map.tags.role }}'
      loop_control:
        loop_var: reset
  vars_prompt:
    - name: prompt_remove_packages
      prompt: Remove installed apt packages? [Y/n]
      default: 'n'
      private: false
