---
- name: Ansible Vault
  hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
    - name: playbook_action
      prompt: "Select an action to perform:\n
        1) List encrypted variables\n
        2) Encrypt variable\n
        3) Update global password\n"
      private: false
  tasks:
    - name: Encrypted Variables
      when: playbook_action in ['1', '1)']
      block:
        - name: Set encrypted variables fact
          ansible.builtin.set_fact:
            encrypted_variables:
              password_argocd_admin: '{{ password_argocd_admin }}'
              password_argocd_user: '{{ password_argocd_user }}'
              password_grafana_admin: '{{ password_grafana_admin }}'
              credential_cloudflare_api_token: '{{ credential_cloudflare_api_token }}'
              credential_postfix_alias: '{{ credential_postfix_alias }}'
              credential_postfix_name: '{{ credential_postfix_name }}'
              credential_postfix_password: '{{ credential_postfix_password }}'
              credential_slack_webhook_url: '{{ credential_slack_webhook_url }}'
              credential_longhorn_backup_password: '{{ credential_longhorn_backup_password }}'
          no_log: true

        - name: List encrypted variables
          ansible.builtin.debug:
            var: encrypted_variables

    - name: Encrypt Variable
      when: playbook_action in ['2', '2)']
      block:
        - name: Set variable key and value
          ansible.builtin.pause:
            prompt: Set variable with a 'key|value' format
          register: variable

        - name: Encrypt variable
          ansible.builtin.command:
            cmd: >-
              ansible-vault encrypt_string {{ variable.user_input | split('|') | last | quote }}
                -n {{ variable.user_input | split('|') | first | quote }}
          register: encrypted_variable
          changed_when: false
          no_log: true

        - name: List encrypted variable
          ansible.builtin.debug:
            var: encrypted_variable.stdout

    - name: Global Password
      when: playbook_action in ['3', '3)']
      block:
        - name: Update global password
          ansible.builtin.pause:
            prompt: '{{ item }}'
            echo: false
          loop:
            - 'New global password'
            - 'Confirm new global password'
          register: password

        - name: Validate password
          ansible.builtin.assert:
            that: password.results[0].user_input == password.results[1].user_input
            fail_msg: Passwords do not match.
            quiet: true

        - name: Create password file
          ansible.builtin.tempfile:
            path: .
          register: vault_file

        - name: Set new global password
          ansible.builtin.lineinfile:
            line: '{{ password.results[0].user_input }}'
            path: '{{ vault_file.path }}'
            mode: '0644'
          no_log: true

        - name: Update global password
          ansible.builtin.command:
            cmd: >-
              ansible-vault encrypt_string {{ item.value | quote }}
                -n {{ item.key | quote }} --vault-pass-file {{ vault_file.path }}
          loop:
            - key: password_argocd_admin
              value: '{{ password_argocd_admin }}'
            - key: password_argocd_user
              value: '{{ password_argocd_user }}'
            - key: password_grafana_admin
              value: '{{ password_grafana_admin }}'
            - key: credential_cloudflare_api_token
              value: '{{ credential_cloudflare_api_token }}'
            - key: credential_postfix_alias
              value: '{{ credential_postfix_alias }}'
            - key: credential_postfix_name
              value: '{{ credential_postfix_name }}'
            - key: credential_postfix_password
              value: '{{ credential_postfix_password }}'
            - key: credential_slack_webhook_url
              value: '{{ credential_slack_webhook_url }}'
            - key: credential_longhorn_backup_password
              value: '{{ credential_longhorn_backup_password }}'
          register: encrypted_variables
          changed_when: false
          no_log: true

        - name: Remove password file
          ansible.builtin.file:
            path: '{{ vault_file.path }}'
            state: absent

        - name: List encrypted role variables
          ansible.builtin.debug:
            var: encrypted_variables.results | map(attribute='stdout')
