---
coredns_vars:
  kubernetes:
    helm:
      chart:
        name: coredns
        version: '{{ coredns_chart_version | default("v1.45.2") }}'
      repository:
        name: helm
        org: coredns
        url: https://coredns.github.io
    hpa:
      # -- If `false`, `replicas` value is set from `min_replicas` value
      enabled: true
      min_replicas: '{{ coredns_hpa_min_replicas | default(defaults.coredns.hpa_min_replicas) }}'
      max_replicas: '{{ coredns_hpa_max_replicas | default(defaults.coredns.hpa_max_replicas) }}'
      resource:
        name: memory
        target:
          # -- Average utilization percentage
          utilization: 80
    deployment:
      # -- Legacy deployment, using `kube-dns` label selectors
      legacy: false
    namespace: kube-system
    resources: '{{ defaults.cluster.pod_resources.small }}'
