---
- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml
  any_errors_fatal: true

- name: User Configuration
  ansible.builtin.import_tasks:
    file: user.yaml

- name: Proxy Configuration
  ansible.builtin.import_tasks:
    file: proxy.yaml

- name: Cluster Provisioning
  block:
    - name: Cluster Configuration
      ansible.builtin.import_tasks:
        file: configuration.yaml

    - name: Cluster Upgrade
      ansible.builtin.import_tasks:
        file: upgrade.yaml
