---
metricsserver_vars:
  kubernetes:
    helm:
      chart:
        name: metrics-server
        version: '{{ metrics_server_chart_version | default("v3.13.0") }}'
      repository:
        name: metrics-server
        org: kubernetes-sigs
        url: https://kubernetes-sigs.github.io
    namespace: kube-system
    replicas: 1
    resources: '{{ defaults.cluster.pod_resources.small }}'
    server:
      # -- Additional server arguments,
      # set log level [verbosity](https://google.github.io/glog/stable/logging/#verbose-logging)
      args:
        - --v=1
      tls:
        # -- Available options are `cert-manager`, `helm` and `metrics-server`
        type: '{{ metrics_server_tls_type | default(defaults.metrics_server.tls_type) }}'
